"""GitHub module — .gitignore and README templates for paper repos."""
from __future__ import annotations

LATEX_GITIGNORE = """\
# LaTeX compilation artifacts
*.aux
*.log
*.out
*.toc
*.bbl
*.blg
*.synctex.gz
*.fdb_latexmk
*.fls
*.nav
*.snm
*.vrb
*.bcf
*.run.xml

# Overleaf sync metadata (IMPORTANT: prevents compilation artifacts from polluting git)
.overleaf/

# Generated PDF — tracked separately on releases, not in commits
*.pdf

# Large data files
replication/data/*.csv

# Environment
.env
__pycache__/
*.pyc
.DS_Store
"""


def render_readme(
    paper_title: str,
    paper_id: str,
    github_username: str = "",
) -> str:
    return f"""\
# {paper_title}

Generated by [E2ER v3](https://github.com/bhanneke/E2ER-project) — End-to-End Researcher pipeline.

> **Note:** This manuscript was generated with the E2ER pipeline and has undergone
> automated review but has not yet been submitted to a journal.

## Overleaf

To edit this paper in Overleaf:

1. Go to **Overleaf → New Project → Import from GitHub**
2. Select **this repository**
3. Overleaf will sync automatically

> ⚠️ **Important:** Always import into Overleaf FROM GitHub (not the other way around).
> If you create the project in Overleaf first and then connect GitHub, Overleaf will use
> its own repository structure that conflicts with E2ER's replication package layout.
>
> When pushing changes from Overleaf back to GitHub, the `.gitignore` in this repo
> prevents compilation artifacts (`*.aux`, `*.log`, `.overleaf/`) from being committed.

## Replication Package

See [`replication/`](replication/) for:
- `data_queries.sql` — all database queries used in this paper
- `estimation.py` — main econometric specification
- `audit_log.csv` — complete data access audit trail (Allium queries + approvals)
- `data/` — sample datasets used for estimation

## Attribution

This manuscript was generated with the [End-to-End Researcher (E2ER)](https://github.com/bhanneke/E2ER-project)
pipeline developed by Björn Hanneke (hanneke@wiwi.uni-frankfurt.de).

We gratefully acknowledge **Allium** for supporting this research through data access
and technical collaboration.

---
*Paper ID: `{paper_id}`*
"""
